### ISSUE TITLE
TODO list of `Float`

### ISSUE THREAD

**Issue by QianyangPeng** [kframework/wasm-semantics#139]
Here is a list of float related functionalities that are tricky to implement with our the current design.

Parsing
--------
1. Negative NaN (-nan): This should represents a `canonical NaN` whose sign bit is 1.
2. Arithmetic NaN (&plusmn;nan:0x): When "&plusmn;nan" is followed by a colon `:`, then it shall be followed by a `hexnum` representing the `payload` of corresponding NaN.
3. Hexfloat (‘0x’ 𝑝:hexnum ‘.’ 𝑞:hexfrac (‘P’ | ‘p’) ±:sign 𝑒:num):  This is a Float represented in hexadecimal form.

Currently in `K` I don't see an approach to control the `sign bit` or the `payload` of an `NaN`, so maybe there is no direct way to implement negative NaN and Arithmetic NaN.

Conversions
------------
1. Reinterpret (i32.reinterpret_f32, i64.reinterpret_f64, f32.reinterpret_i32, f64.reinterpret_i64): These operations cast the type of a `val` between int and float but keep the binary representation. For example, `i32.reinterpret_f32 (f32.const 1.5) = <i32> 1069547520`

Memory
--------
1. Store (fxx.store): This should store a float number into memory byte by byte.
2. Load (fxx.load): This should load a float number from memory.

If you have any idea how to implement any of the above, please comment below, thanks!

**Comment by dwightguth** [comment]
mpfr doesn't support NaN payloads, so we would have to implement this by means of using system floats and doubles. It's doable, but requires significant work on the K backend, and would only work for these two bit widths of floats.

My advice would be to implement this functionality in the llvm and haskell backends and try to avoid implementing it in the java or ocaml backends.

**Comment by hjorthjort** [comment]
What does the spec say about nondeterminism when dealing with NaN? If we don't have to be able to perform deterministic computations on them we could just represent them as bytes (`Int`s), which also makes storing to memory and reinterpreting simple.

**Comment by QianyangPeng** [comment]
@hjorthjort Can you elaborate how to represent them as bytes (Ints)? I think we have to perform deterministic computations on them though.

**Comment by hjorthjort** [comment]
> @hjorthjort Can you elaborate how to represent them as bytes (Ints)? I think we have to perform deterministic computations on them though.

Well, memory for example is just a map containing integers between 0 and 255, which is like bytes. If we don't need to perform deterministic computation on them, only be able store them and convert them, it would be the exact same conversion we use to transform `Int` to and from memory bytes.

**Comment by QianyangPeng** [comment]
Ah I see. Yeah. But for a common `Float`, for example, <f64> 1.5, how to store it into memory then?
