### ISSUE TITLE
Clarify division in wasm.md

### ISSUE THREAD

**Issue by axic** [kframework/wasm-semantics#14]
This is against the repo-organization branch:

 ```k
    syntax IBinOp ::= "div_s" | "rem_s"
 // -----------------------------------
    rule <k> ITYPE . div_s I1 I2
          => #if I2 =/=Int 0 andBool (I1 =/=Int #pow1(ITYPE) orBool (I2 =/=Int #pow(ITYPE) -Int 1))
                #then < ITYPE > #unsigned(ITYPE, #signed(ITYPE, I1) /Int #signed(ITYPE, I2))
                #else undefined
             #fi
         ...
         </k>
```

It would probably be nicer to negate the conditions here and in `div_u`/`rem_u` too.

Additionally, it probably makes sense having a comment explaining those two edge cases, just like the wasm spec is doing.

**Comment by hjorthjort** [comment]
This seems to have been made cleaner with the new implementation: https://github.com/kframework/wasm-semantics/blob/master/numeric.md#binary-operators

If you disagree, please re-open.
