### ISSUE TITLE
Set up LLVM backend, make default if possible

### ISSUE THREAD

**Issue by ehildenb** [kframework/wasm-semantics#151]
Find a minimal definition which exibits this bug.

Steps to do so:

1.  Come up with a minimal Wasm test case which exhibits this bug, we want to require as little of the semantics as possible to demonstrate this bug.
2.  Start deleting rules from the semantics until you can't delete any more while still demonstrating the bug.
3.   Start deleting syntax from the semantics until you can't delete any more.
4.   Combine all the modules into 1 module.
5.   Re-minimize the rules/syntax.

**Comment by hjorthjort** [comment]
@ehildenb Is this done?

**Comment by ehildenb** [comment]
Yes this is done.
