### ISSUE TITLE
Could not find main module with name WASM in definition.

### ISSUE THREAD

**Issue by xiangbeibei** [kframework/wasm-semantics#16]
when  input "make build", it just told  "[Error] Compiler: Could not find main module with name WASM in definition." Please tell me something with the error, Thanks.

**Comment by ehildenb** [comment]
Can you try `make defn -B`? Are you getting errors about `pandoc` then?

If you get errors with `pandoc`, you need to first install Pandoc, then run `make deps`, then `make denf -B`, then `make build`. After it works once, you should only need to run `make build` in the future.

**Comment by xiangbeibei** [comment]
It's all right. Thanks for your help.
