### ISSUE TITLE
Inner Parser

### ISSUE THREAD

**Issue by xiangbeibei** [kframework/wasm-semantics#17]
There comes to a new issue. 
When using 'kwasm'  to run the files under directory /tests/simple/,
for example, file 'arithmetic.wast', it gives me like this:
[Error] Critical: Parser returned a non-zero exit code: 113
Stdout:
Stderr:
[Error] Inner Parser: Scanner error: unexpected character sequence '#'.
	Source(/wasm-semantics/tests/simple/arithmetic.wast)
	Location(4,1,4,2)
So whether something input is wrong or not? Or what is the matter?
Thanks~

**Comment by xiangbeibei** [comment]
And also there is an issue about  [Error] Inner Parser: Scanner error: unexpected token 'module'.

**Comment by ehildenb** [comment]
Ah, this is because it uses the definition in `.build/defn/test` for running tests, which includes things like the assertions (which start with `#`).

Try out branch `module-semantics`. It should auto-detect the correct version of the semantics to run.

**Comment by xiangbeibei** [comment]
But whether I 'make deps' again?
When I try to 'make deps', it puts like this:
fatal: 引用不是一个树：ffa737e267b59499adeeff9ea5d56d1ded91b357
无法在子模组路径 '.build/k' 中检出 'ffa737e267b59499adeeff9ea5d56d1ded91b357'
Makefile:31: recipe for target '/home/xbb/ws/wasm-semantics/.build/k/make.timestamp' failed
make: *** [/home/xbb/ws/wasm-semantics/.build/k/make.timestamp] Error 1

**Comment by ehildenb** [comment]
Sorry, forgot to push up the correct K submodule. Do `git pull`, then `rm .build/k/make.timestamp`, then `make deps`, and it should work now.
