### ISSUE TITLE
#unparseWasmString not supported in java backend

### ISSUE THREAD

**Issue by MrChico** [kframework/wasm-semantics#191]
The conversion between K `String`s and `WasmString` does not work in the java backend, probably to do with the fact that it is only defined by the `[hook.token2string]`

**Comment by hjorthjort** [comment]
Can you check that this is still true if you checkout the `wasm-token-sorts` branch?

**Comment by MrChico** [comment]
I experienced this in trying https://github.com/kframework/ewasm-semantics/blob/initial/tests/simple/basic_invocation.wast. With `wasm-token-sorts` that example instead crashes with a Z3 error: `(error "line 12 column 11: Sorts Int and WasmString are incompatible")`. This does happen a lot though, and does not necessarily mean that `wasm-token-sorts` is done bad

**Comment by hjorthjort** [comment]
@MrChico Can you check if this PR fixed the issue?
https://github.com/kframework/wasm-semantics/pull/212

**Comment by hjorthjort** [comment]
Java backend deprecated. Closing.
