### ISSUE TITLE
List of issues with WRC20 spec

### ISSUE THREAD

**Issue by ehildenb** [kframework/wasm-semantics#238]
Currently we have the WRC20 spec thanks to #235, but it has several issues. @hjorthjort can you make a list of the parsing issues it faces (the manual changes you needed to make to the Wasm code)?

**Comment by hjorthjort** [comment]
To get it to parse, I take these steps:

1. Pass the concrete file (https://gist.github.com/poemm/823566e89def007daa5d97ac5bd14419#file-wrc20_handwritten_fast_transfer-wat) to `./kwasm kast <FILE> pretty`
2. Split the output by words, and for each word do the following:
   1. Check if the word starts with `0x` -- if so, interpret it as hex and change to decimal, e.g. the selector `0x1a029399` for `$do_balance` becomes `436376473`.
   2. Check if the word starts with `$` -- if so, change it from `$foo` to `DOLLAR__FOO`. TODO: also add a constraint that all these variables are different.
   3. If a word contains a string, i.e. `"something"`, change it to `#unparseWasmString("\"something\"")`
