### ISSUE TITLE
Add `syntax Stmts ::= "WRC20" [function]`

### ISSUE THREAD

**Issue by ehildenb** [kframework/wasm-semantics#241]
Because we'll be writing several specifications over the WRC20 code, we need to abstract out the actual code to load into a K function which expands out to the correct code.

**Comment by hjorthjort** [comment]
@ehildenb Should it be macros rather than functions? Since function application can not be part of the left-hand side of a rule, I suspect we will have problems if we try to write specs like `#wrc20() => .`
