### ISSUE TITLE
Add conversion instructions

### ISSUE THREAD

**Issue by hjorthjort** [kframework/wasm-semantics#36]
The following instructions are called "conversion instructions". They are currently not implemented.
 ```
i32.wrap_i64                         f32.demote_f64
i64.extend_i32_[u/s]                 f64.promote_f32         
i[32/64].trunc_f[32/64]_[u/s]        f[32/64]_convert_i[32/64]_[u/s]
i[32/64].reinterpret_f[32/64]        f[32/64]_reinterpret_i[32/64]
```

**Comment by hjorthjort** [comment]
Most of these deal with floating point numbers in some way. For eWasm, they are less of a priority, but I still think they should be included for completeness.

However, of them are pure integer instructions, namely `i32.wrap_i64` and `i64.extend_i32_[u/s]`, and should be prioritized.

Regarding `demote`, `trunc`, and `reinterpret`, does K have built-ins that could deal with them?

**Comment by dwightguth** [comment]
I imagine that bitRangeInt and signedBitRangeInt will be of interest to you.

**Comment by ehildenb** [comment]
The integer conversion operators are implemented now, only the floating point ones remain.

**Comment by hjorthjort** [comment]
Since only floating point remains, let's close this. We could have a "implement all the floating point semantics" issue if we want, but for now, this issue should be considered resolved.
