### ISSUE TITLE
Tests in tests/wasm-tests/test/core needs attention.

### ISSUE THREAD

**Issue by QianyangPeng** [kframework/wasm-semantics#77]
The test files under tests/wasm-tests/test/core (hereinafter called the **core test files**) are provided as standard test files by the WebAssembly repo and could be interpreted by the WASM Reference Interpreter. But the tests syntax are a little bit different with the standard wasm syntax (S-expression syntax). More details could be found at wasm-semantics/tests/wasm-tests/interpreter/README.md.

1. `invoke`

- According to the specification, `invoke` is an administrative instruction (which means a internal helper instruction) that calls a function directly by its `address` on the `store`. It ignores the current closure and should never be used directly.

- In the core test files, `invoke` is used to invoke a **exported** function by its `name`:

    `( invoke <name>? <string> <expr>* )        ;; invoke function export`

    `invoke` under these 2 definitions have different meanings and should be treated separately.

2. `get`

- According to the specification, `global.get` is used to get a global, and `get` by itself is undefined.

- In the core test files, `get` is used to get an **exported** global.

2. `func`

- The declaration of functions in core test files are usually:

    `(module (func (export "f") (param i32 i32) (result i32) (i32.add (local.get 0) (local.get 1))))`

    which will be transformed into:

```
    (module
    (type $0 (func (param i32 i32) (result i32)))
    (func $0 (type 0) (local.get 0) (local.get 1) (i32.add))
    (export "f" (func 0))
    )
```

To be continued

**Comment by hjorthjort** [comment]
Good documentation.
Also note that currently, we force parentheses around every instruction, e.g.
```
(i32.const 1)
(i32.const 2)
(i32.add)
```
The reason is that it fits well with the folded syntax:
```
(i32.add (i32.const) (i32.const))
```

However, it's perfectly valid to write the following in WebAssembly concrete syntax:

```
i32.const 1
i32.const 2
i32.add
```
Note the lack of parentheses.
