### ISSUE TITLE
Enable *not* running tests when building

### ISSUE THREAD

**Issue by hjorthjort** [kframework/wasm-semantics#80]
It seems running `.build` always runs the entire test suite. That seems overkill and slows down development time. Could an optional flag be added for disabling running the tests?
@nishantjr

**Comment by nishantjr** [comment]
`./build ocaml haskell java` will build just the definitions. We can add `proj.alias(name = 'definitions', targets = [ocaml, haskell, java])` to allow building just the definitions: `./build definitions`

**Comment by nishantjr** [comment]
When I am developing I usually concentrate on a single test, and use something like `./build .build/tests/wasm-tests/test/core/forward.wast.wasm-java-run.test`
This will build just the definition that the particular test depends on.

We could also add an alias to make this easier: maybe `./build tests/wasm-tests/test/core/forward.wast.test-conformance` or similar

**Comment by hjorthjort** [comment]
> `./build ocaml haskell java` will build just the definitions. We can add also `proj.alias(name = 'definitions', targets = [ocaml, haskell, java])` to allow building just the definitions with `./build definitions`

I'm in favor of this. Especially since that means the command doesn't have to change if we add backends.



> When I am developing I usually concentrate on a single test, and use something like `./build .build/tests/wasm-tests/test/core/forward.wast.wasm-java-run.test`
> This will build just the definition that the particular test depends on.
> 
> We could also add an alias to make this easier: maybe `./build tests/wasm-tests/test/core/forward.wast.test-conformance` or similar

Thanks for the advice. That seems like a good way to do it. But I'm also generally in favor of having flags for the most common/expected behavior. While it makes sense for me to learn the build tools, we also want to enable people to check out and play with the project, focusing on the semantics and running/proving programs without having to get too familiar with the build system.

**Comment by hjorthjort** [comment]
Is there any additional configuration needed? This happened when I tried just building the definitions:

```
$ ./build ocaml haskell java
ninja: error: unknown target 'ocaml'
```

**Comment by nishantjr** [comment]
Ah sorry, with the wasm configuration it is `./build wasm-ocaml wasm-haskell wasm-java`. (It's the alias parameter to the `definition` function.)

Just adding `proj.alias(name = 'definitions', targets = [wasm_ocaml, wasm_haskell, wasm_java])`
to `./build` will get you the behaviour we talked about previously.
