### ISSUE TITLE
Get Z3 model?

### ISSUE THREAD

**Issue by jrakow** [kframework/wasm-semantics#86]
Is there a way to get a Z3 encoding of execution out of KWasm?
I would like to reason about the equivalence of non-looping Wasm programs for a project. I was at the talk on the weekend and KWasm peeked my interest.

**Comment by hjorthjort** [comment]
You can pass do a proof by doing
```
/build && ./kwasm klab-prove tests/proofs/simple-arithmetic-spec.k -m KWASM-LEMMAS --debug-z3
```

The `--debug-z3` gives extensive output from Z3, in particular, the claims it manages to prove.

However, not all the reasoning happens at the Z3 level, it is only used for checking satisfiability of conditions, e.g. the ones introduced after conditional branching. Much of the reasoning happens inside the K prover.

Another good place to ask questions (that may also get quicker replies) is in the K chat <https://riot.im>/app/#/room/#k:matrix.org>

**Comment by jrakow** [comment]
Alright. Thanks.
