### ISSUE TITLE
Supporting `import` and multiple modules.

### ISSUE THREAD

**Issue by QianyangPeng** [kframework/wasm-semantics#99]
Objective: Handle the test cases in wasm-semantics/tests/wasm-tests/test/core/import.wast

In official test cases, they support the functionality of "registering" a recently defined module, and only then the module could be used for imports. In other word, multiple module instances should be supported in order to implement `import`.

"register" gives module a name, so that `import` will know the module name to be imported from.

**Comment by hjorthjort** [comment]
Example from `imports.wast`:
```
(module
  (func (export "func"))
  (func (export "func-i32") (param i32))
  (func (export "func-f32") (param f32))
  (func (export "func->i32") (result i32) (i32.const 22))
  (func (export "func->f32") (result f32) (f32.const 11))
  (func (export "func-i32->i32") (param i32) (result i32) (local.get 0))
  (func (export "func-i64->i64") (param i64) (result i64) (local.get 0))
  (global (export "global-i32") i32 (i32.const 55))
  (global (export "global-f32") f32 (f32.const 44))
  (table (export "table-10-inf") 10 funcref)
  ;; (table (export "table-10-20") 10 20 funcref)
  (memory (export "memory-2-inf") 2)
  ;; (memory (export "memory-2-4") 2 4)
)

(register "test")
```
and later

```
(module (import "test" "func" (func)))
(module (import "test" "func-i32" (func (param i32))))
```

**Comment by hjorthjort** [comment]
Highly related to #77. We should do a drive to get these auxilliary expressions inot the test file.
